In [4]:
import pandas as pd
import numpy as np
%pylab inline

## READING data
path = '~/Desktop/1st_Kaggle/Rossman/train.csv'
data = pd.read_csv(path)
path_store = '~/Desktop/1st_Kaggle/Rossman/store.csv'
data_store = pd.read_csv(path_store)

Populating the interactive namespace from numpy and matplotlib

<bound method DataFrame.head of       Store StoreType Assortment  CompetitionDistance  \
0         1         c          a                 1270
1         2         a          a                  570
2         3         a          a                14130
3         4         c          c                  620
4         5         a          a                29910
5         6         a          a                  310
6         7         a          c                24000
7         8         a          a                 7520
8         9         a          c                 2030
9        10         a          a                 3160
10       11         a          c                  960
11       12         a          c                 1070
12       13         d          a                  310
13       14         a          a                 1300
14       15         d          c                 4110
15       16         a          c                 3270
16       17         a          a                   50
17       18         d          c                13840
18       19         a          c                 3240
19       20         d          a                 2340
20       21         c          c                  550
21       22         a          a                 1040
22       23         d          a                 4060
23       24         a          c                 4590
24       25         c          a                  430
25       26         d          a                 2300
26       27         a          a                   60
27       28         a          a                 1200
28       29         d          c                 2170
29       30         a          a                   40
...     ...       ...        ...                  ...
1085   1086         a          a                  180
1086   1087         d          c                 2210
1087   1088         a          a                 4300
1088   1089         d          a                 5220
1089   1090         a          a                  330
1090   1091         a          c                 9990
1091   1092         a          a                  300
1092   1093         c          c                10450
1093   1094         d          a                 2380
1094   1095         a          a                  690
1095   1096         a          c                 1130
1096   1097         b          b                  720
1097   1098         a          a                 1830
1098   1099         a          c                  200
1099   1100         a          a                  540
1100   1101         d          c                 4060
1101   1102         a          a                  850
1102   1103         d          c                 1340
1103   1104         d          a                  260
1104   1105         c          c                  330
1105   1106         a          c                 5330
1106   1107         a          a                 1400
1107   1108         a          a                  540
1108   1109         c          a                 3490
1109   1110         c          c                  900
1110   1111         a          a                 1900
1111   1112         c          c                 1880
1112   1113         a          c                 9260
1113   1114         a          c                  870
1114   1115         d          c                 5350

      CompetitionOpenSinceMonth  CompetitionOpenSinceYear  Promo2  \
0                             9                      2008       0
1                            11                      2007       1
2                            12                      2006       1
3                             9                      2009       0
4                             4                      2015       0
5                            12                      2013       0
6                             4                      2013       0
7                            10                      2014       0
8                             8                      2000       0
9                             9                      2009       0
10                           11                      2011       1
11                          NaN                       NaN       1
12                          NaN                       NaN       1
13                            3                      2014       1
14                            3                      2010       1
15                          NaN                       NaN       0
16                           12                      2005       1
17                            6                      2010       1
18                          NaN                       NaN       1
19                            5                      2009       1
20                           10                      1999       1
21                          NaN                       NaN       1
22                            8                      2005       0
23                            3                      2000       1
24                            4                      2003       0
25                          NaN                       NaN       0
26                            1                      2005       1
27                           10                      2014       1
28                          NaN                       NaN       0
29                            2                      2014       1
...                         ...                       ...     ...
1085                         11                      2013       1
1086                         11                      2011       0
1087                          3                      2009       1
1088                          5                      2009       0
1089                        NaN                       NaN       1
1090                        NaN                       NaN       0
1091                          7                      2000       1
1092                          6                      2009       0
1093                          3                      2013       1
1094                          6                      2007       1
1095                        NaN                       NaN       1
1096                          3                      2002       0
1097                         11                      2004       0
1098                          4                      2013       1
1099                        NaN                       NaN       1
1100                          9                      2012       0
1101                         11                      2012       1
1102                         10                      2006       1
1103                          2                      2012       1
1104                         11                      2008       1
1105                          9                      2011       1
1106                          6                      2012       1
1107                          4                      2004       0
1108                          4                      2011       1
1109                          9                      2010       0
1110                          6                      2014       1
1111                          4                      2006       0
1112                        NaN                       NaN       0
1113                        NaN                       NaN       0
1114                        NaN                       NaN       1

      Promo2SinceWeek  Promo2SinceYear     PromoInterval
0                 NaN              NaN               NaN
1                  13             2010   Jan,Apr,Jul,Oct
2                  14             2011   Jan,Apr,Jul,Oct
3                 NaN              NaN               NaN
4                 NaN              NaN               NaN
5                 NaN              NaN               NaN
6                 NaN              NaN               NaN
7                 NaN              NaN               NaN
8                 NaN              NaN               NaN
9                 NaN              NaN               NaN
10                  1             2012   Jan,Apr,Jul,Oct
11                 13             2010   Jan,Apr,Jul,Oct
12                 45             2009   Feb,May,Aug,Nov
13                 40             2011   Jan,Apr,Jul,Oct
14                 14             2011   Jan,Apr,Jul,Oct
15                NaN              NaN               NaN
16                 26             2010   Jan,Apr,Jul,Oct
17                 14             2012   Jan,Apr,Jul,Oct
18                 22             2011  Mar,Jun,Sept,Dec
19                 40             2014   Jan,Apr,Jul,Oct
20                 45             2009   Jan,Apr,Jul,Oct
21                 22             2012   Jan,Apr,Jul,Oct
22                NaN              NaN               NaN
23                 40             2011   Jan,Apr,Jul,Oct
24                NaN              NaN               NaN
25                NaN              NaN               NaN
26                  5             2011   Jan,Apr,Jul,Oct
27                  6             2015  Mar,Jun,Sept,Dec
28                NaN              NaN               NaN
29                 10             2014  Mar,Jun,Sept,Dec
...               ...              ...               ...
1085               18             2011   Feb,May,Aug,Nov
1086              NaN              NaN               NaN
1087               27             2013   Jan,Apr,Jul,Oct
1088              NaN              NaN               NaN
1089               14             2011   Jan,Apr,Jul,Oct
1090              NaN              NaN               NaN
1091               40             2014   Jan,Apr,Jul,Oct
1092              NaN              NaN               NaN
1093               40             2014   Jan,Apr,Jul,Oct
1094               14             2011   Jan,Apr,Jul,Oct
1095               10             2014  Mar,Jun,Sept,Dec
1096              NaN              NaN               NaN
1097              NaN              NaN               NaN
1098               14             2013   Jan,Apr,Jul,Oct
1099               14             2011   Jan,Apr,Jul,Oct
1100              NaN              NaN               NaN
1101               40             2014   Jan,Apr,Jul,Oct
1102                5             2013   Feb,May,Aug,Nov
1103               14             2011   Jan,Apr,Jul,Oct
1104                5             2013   Feb,May,Aug,Nov
1105               31             2013   Jan,Apr,Jul,Oct
1106               13             2010   Jan,Apr,Jul,Oct
1107              NaN              NaN               NaN
1108               22             2012   Jan,Apr,Jul,Oct
1109              NaN              NaN               NaN
1110               31             2013   Jan,Apr,Jul,Oct
1111              NaN              NaN               NaN
1112              NaN              NaN               NaN
1113              NaN              NaN               NaN
1114               22             2012  Mar,Jun,Sept,Dec

[1115 rows x 10 columns]>